import { adminStats, adminMonthlyData, formatCurrency, mockClaims } from '@/lib/mockData';
import { StatCard } from '@/components/DashboardWidgets';
import { Users, FileText, IndianRupee, Zap, Download } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line } from 'recharts';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';

function downloadCSV() {
  const headers = ['Month', 'Users', 'Payouts (₹)', 'Trigger Events'];
  const rows = adminMonthlyData.map(d => [d.month, d.users, d.payouts, d.triggers].join(','));
  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'incomeshield_admin_data.csv';
  a.click();
  URL.revokeObjectURL(url);
  toast.success('CSV downloaded!');
}

function downloadPDF() {
  // Generate a simple HTML-based PDF
  const content = `
    <html><head><title>IncomeShield Admin Report</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
      h1 { color: #1a2654; margin-bottom: 8px; }
      h2 { color: #555; font-size: 14px; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin: 20px 0; }
      th, td { border: 1px solid #ddd; padding: 10px 14px; text-align: left; }
      th { background: #1a2654; color: white; }
      .summary { display: flex; gap: 20px; margin: 20px 0; }
      .stat { background: #f5f5f5; padding: 16px; border-radius: 8px; flex: 1; }
      .stat p { margin: 0; }
      .stat .label { color: #888; font-size: 12px; }
      .stat .value { font-size: 24px; font-weight: bold; }
    </style></head><body>
    <h1>IncomeShield — Admin Report</h1>
    <h2>Platform Analytics & Payout Summary</h2>
    <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:12px;margin-bottom:24px;">
      <div class="stat"><p class="label">Total Users</p><p class="value">${adminStats.totalUsers.toLocaleString()}</p></div>
      <div class="stat"><p class="label">Active Policies</p><p class="value">${adminStats.activePolicies.toLocaleString()}</p></div>
      <div class="stat"><p class="label">Total Payouts</p><p class="value">₹${adminStats.totalPayouts.toLocaleString('en-IN')}</p></div>
      <div class="stat"><p class="label">Trigger Events</p><p class="value">${adminStats.triggerEvents}</p></div>
    </div>
    <table>
      <thead><tr><th>Month</th><th>Users</th><th>Payouts (₹)</th><th>Trigger Events</th></tr></thead>
      <tbody>${adminMonthlyData.map(d => `<tr><td>${d.month}</td><td>${d.users.toLocaleString()}</td><td>₹${d.payouts.toLocaleString('en-IN')}</td><td>${d.triggers}</td></tr>`).join('')}</tbody>
    </table>
    <p style="color:#888;font-size:11px;margin-top:40px;">Generated by IncomeShield Admin Dashboard • ${new Date().toLocaleDateString('en-IN')}</p>
    </body></html>`;
  const blob = new Blob([content], { type: 'application/pdf' });
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.print();
  }
  toast.success('PDF report opened for print/download');
}

export default function AdminPage() {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Admin Dashboard</h1>
        <p className="text-muted-foreground">Platform-wide metrics and analytics</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard title="Total Users" value={adminStats.totalUsers.toLocaleString()} icon={Users} variant="default" />
        <StatCard title="Active Policies" value={adminStats.activePolicies.toLocaleString()} icon={FileText} variant="accent" />
        <StatCard title="Total Payouts" value={formatCurrency(adminStats.totalPayouts)} icon={IndianRupee} variant="safe" />
        <StatCard title="Trigger Events" value={adminStats.triggerEvents.toString()} subtitle="Last 30 days" icon={Zap} variant="warning" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="elevated-card rounded-xl p-6">
          <h3 className="text-sm font-semibold text-foreground mb-4">User Growth & Payouts (6 Months)</h3>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={adminMonthlyData}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="month" tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <YAxis yAxisId="left" tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <YAxis yAxisId="right" orientation="right" tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <Tooltip formatter={(val: number, name: string) => name === 'Payouts' ? formatCurrency(val) : val.toLocaleString()} />
              <Bar yAxisId="left" dataKey="users" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} name="Users" />
              <Bar yAxisId="right" dataKey="payouts" fill="hsl(var(--safe))" radius={[4, 4, 0, 0]} name="Payouts" />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="elevated-card rounded-xl p-6">
          <h3 className="text-sm font-semibold text-foreground mb-4">Trigger Events Trend</h3>
          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={adminMonthlyData}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="month" tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <YAxis tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <Tooltip />
              <Line type="monotone" dataKey="triggers" stroke="hsl(var(--warning))" strokeWidth={2} dot={{ fill: 'hsl(var(--warning))' }} name="Triggers" />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="elevated-card rounded-xl p-5 text-center">
          <p className="text-sm text-muted-foreground">Avg. Premium</p>
          <p className="text-3xl font-bold text-foreground">{formatCurrency(adminStats.avgPremium)}</p>
          <p className="text-xs text-muted-foreground">per week per user</p>
        </div>
        <div className="elevated-card rounded-xl p-5 text-center">
          <p className="text-sm text-muted-foreground">Claim Ratio</p>
          <p className="text-3xl font-bold text-warning">{(adminStats.claimRatio * 100).toFixed(0)}%</p>
          <p className="text-xs text-muted-foreground">of policies claimed this month</p>
        </div>
        <div className="elevated-card rounded-xl p-5 text-center">
          <p className="text-sm text-muted-foreground">Fraud Detection Rate</p>
          <p className="text-3xl font-bold text-safe">2.1%</p>
          <p className="text-xs text-muted-foreground">of claims flagged</p>
        </div>
      </div>

      {/* Download Section */}
      <div className="elevated-card rounded-xl p-6">
        <h3 className="text-sm font-semibold text-foreground mb-2">Export Data</h3>
        <p className="text-sm text-muted-foreground mb-4">Download all platform data for reporting and analysis</p>
        <div className="flex flex-wrap gap-3">
          <Button onClick={downloadCSV} variant="outline" className="gap-2">
            <Download className="h-4 w-4" />
            Download CSV (Excel)
          </Button>
          <Button onClick={downloadPDF} variant="outline" className="gap-2">
            <Download className="h-4 w-4" />
            Download PDF Report
          </Button>
        </div>
      </div>
    </div>
  );
}
