import { useState, useEffect } from 'react';
import { adminStats, adminMonthlyData, formatCurrency, mockClaims } from '@/lib/mockData';
import { StatCard } from '@/components/DashboardWidgets';
import { Users, FileText, IndianRupee, Zap, Download, Lock, ShieldAlert, AlertTriangle, TrendingUp } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, LineChart, Line, PieChart, Pie, Cell } from 'recharts';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { useTranslation } from '@/hooks/useTranslation';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';

function downloadCSV() {
  const headers = ['Month', 'Users', 'Payouts (₹)', 'Trigger Events', 'Claims', 'Premium Collected (₹)'];
  const rows = adminMonthlyData.map(d => [d.month, d.users, d.payouts, d.triggers, d.claims, d.premiumCollected].join(','));
  const csv = [headers.join(','), ...rows].join('\n');
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'incomeshield_admin_data.csv';
  a.click();
  URL.revokeObjectURL(url);
  toast.success('CSV downloaded!');
}

function downloadPDF() {
  const content = `
    <html><head><title>IncomeShield Admin Report</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 40px; color: #333; }
      h1 { color: #1a2654; margin-bottom: 8px; }
      h2 { color: #555; font-size: 14px; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin: 20px 0; }
      th, td { border: 1px solid #ddd; padding: 10px 14px; text-align: left; }
      th { background: #1a2654; color: white; }
      .stat { background: #f5f5f5; padding: 16px; border-radius: 8px; flex: 1; }
      .stat p { margin: 0; }
      .stat .label { color: #888; font-size: 12px; }
      .stat .value { font-size: 24px; font-weight: bold; }
    </style></head><body>
    <h1>IncomeShield — Admin Report</h1>
    <h2>Platform Analytics & Payout Summary</h2>
    <div style="display:grid;grid-template-columns:1fr 1fr 1fr 1fr;gap:12px;margin-bottom:24px;">
      <div class="stat"><p class="label">Total Users</p><p class="value">${adminStats.totalUsers.toLocaleString()}</p></div>
      <div class="stat"><p class="label">Active Policies</p><p class="value">${adminStats.activePolicies.toLocaleString()}</p></div>
      <div class="stat"><p class="label">Total Payouts</p><p class="value">₹${adminStats.totalPayouts.toLocaleString('en-IN')}</p></div>
      <div class="stat"><p class="label">Total Claims</p><p class="value">${adminStats.totalClaims.toLocaleString()}</p></div>
    </div>
    <table>
      <thead><tr><th>Month</th><th>Users</th><th>Payouts (₹)</th><th>Trigger Events</th><th>Claims</th><th>Premium (₹)</th></tr></thead>
      <tbody>${adminMonthlyData.map(d => `<tr><td>${d.month}</td><td>${d.users.toLocaleString()}</td><td>₹${d.payouts.toLocaleString('en-IN')}</td><td>${d.triggers}</td><td>${d.claims}</td><td>₹${d.premiumCollected.toLocaleString('en-IN')}</td></tr>`).join('')}</tbody>
    </table>
    <p style="color:#888;font-size:11px;margin-top:40px;">Generated by IncomeShield Admin Dashboard • ${new Date().toLocaleDateString('en-IN')}</p>
    </body></html>`;
  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(content);
    printWindow.document.close();
    printWindow.print();
  }
  toast.success('PDF report opened for print/download');
}

const platformData = [
  { name: 'Zomato', value: adminStats.partnersZomato },
  { name: 'Swiggy', value: adminStats.partnersSwiggy },
  { name: 'Both', value: adminStats.partnersBoth },
];
const PIE_COLORS = ['hsl(0, 85%, 55%)', 'hsl(35, 95%, 55%)', 'hsl(230, 65%, 50%)'];

export default function AdminPage() {
  const { t } = useTranslation();
  const { user } = useAuth();
  const [isAdmin, setIsAdmin] = useState<boolean | null>(null);

  useEffect(() => {
    async function checkAdmin() {
      if (!user?.id) { setIsAdmin(false); return; }
      const { data } = await supabase.rpc('has_role', { _user_id: user.id, _role: 'admin' });
      setIsAdmin(!!data);
    }
    checkAdmin();
  }, [user?.id]);

  if (isAdmin === null) {
    return (
      <div className="min-h-[60vh] flex items-center justify-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary" />
      </div>
    );
  }

  if (!isAdmin) {
    return (
      <div className="min-h-[70vh] flex items-center justify-center relative">
        <div className="absolute inset-0 backdrop-blur-md bg-background/60 z-10" />
        <div className="relative z-20 flex flex-col items-center gap-6 text-center">
          <div className="w-24 h-24 rounded-full bg-destructive/10 flex items-center justify-center">
            <Lock className="h-12 w-12 text-destructive" />
          </div>
          <h2 className="text-2xl font-bold text-foreground">ONLY ADMINS CAN ACCESS IT</h2>
          <p className="text-muted-foreground max-w-md">
            This page is restricted to administrators only. If you believe you should have access, please contact your platform administrator.
          </p>
        </div>
      </div>
    );
  }

  const totalPremiumCollected = adminMonthlyData.reduce((s, d) => s + d.premiumCollected, 0);

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">{t('adminDashboard')}</h1>
        <p className="text-muted-foreground">{t('platformMetrics')}</p>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard title={t('totalUsers')} value={adminStats.totalUsers.toLocaleString()} icon={Users} variant="default" />
        <StatCard title={t('activePolicies')} value={adminStats.activePolicies.toLocaleString()} icon={FileText} variant="accent" />
        <StatCard title={t('totalPayouts')} value={formatCurrency(adminStats.totalPayouts)} icon={IndianRupee} variant="safe" />
        <StatCard title="Total Claims" value={adminStats.totalClaims.toLocaleString()} icon={ShieldAlert} variant="warning" />
      </div>

      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <StatCard title={t('triggerEvents')} value={adminStats.triggerEvents.toString()} subtitle="Last 30 days" icon={Zap} variant="warning" />
        <StatCard title="Pending Claims" value={adminStats.pendingClaims.toString()} icon={AlertTriangle} variant="default" />
        <StatCard title="Cities Covered" value={adminStats.citiesCovered.toString()} icon={TrendingUp} variant="accent" />
        <StatCard title="Premium Collected" value={formatCurrency(totalPremiumCollected)} subtitle="6 months" icon={IndianRupee} variant="safe" />
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="elevated-card rounded-xl p-6">
          <h3 className="text-sm font-semibold text-foreground mb-4">{t('totalUsers')} & {t('totalPayouts')} (6 Months)</h3>
          <ResponsiveContainer width="100%" height={300}>
            <BarChart data={adminMonthlyData}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="month" tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <YAxis yAxisId="left" tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <YAxis yAxisId="right" orientation="right" tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <Tooltip formatter={(val: number, name: string) => name === 'Payouts' ? formatCurrency(val) : val.toLocaleString()} />
              <Bar yAxisId="left" dataKey="users" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} name="Users" />
              <Bar yAxisId="right" dataKey="payouts" fill="hsl(var(--safe))" radius={[4, 4, 0, 0]} name="Payouts" />
            </BarChart>
          </ResponsiveContainer>
        </div>

        <div className="elevated-card rounded-xl p-6">
          <h3 className="text-sm font-semibold text-foreground mb-4">{t('triggerEvents')} & Claims Trend</h3>
          <ResponsiveContainer width="100%" height={300}>
            <LineChart data={adminMonthlyData}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="month" tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <YAxis tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <Tooltip />
              <Line type="monotone" dataKey="triggers" stroke="hsl(var(--warning))" strokeWidth={2} dot={{ fill: 'hsl(var(--warning))' }} name="Triggers" />
              <Line type="monotone" dataKey="claims" stroke="hsl(var(--primary))" strokeWidth={2} dot={{ fill: 'hsl(var(--primary))' }} name="Claims" />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="elevated-card rounded-xl p-5 text-center">
          <p className="text-sm text-muted-foreground">{t('avgPremium')}</p>
          <p className="text-3xl font-bold text-foreground">{formatCurrency(adminStats.avgPremium)}</p>
          <p className="text-xs text-muted-foreground">per week per user</p>
        </div>
        <div className="elevated-card rounded-xl p-5 text-center">
          <p className="text-sm text-muted-foreground">{t('claimRatio')}</p>
          <p className="text-3xl font-bold text-warning">{(adminStats.claimRatio * 100).toFixed(0)}%</p>
          <p className="text-xs text-muted-foreground">of policies claimed this month</p>
        </div>
        <div className="elevated-card rounded-xl p-5 text-center">
          <p className="text-sm text-muted-foreground">{t('fraudDetection')}</p>
          <p className="text-3xl font-bold text-safe">{(adminStats.fraudRate * 100).toFixed(1)}%</p>
          <p className="text-xs text-muted-foreground">of claims flagged</p>
        </div>
        <div className="elevated-card rounded-xl p-5 text-center">
          <p className="text-sm text-muted-foreground">Avg Payout/Claim</p>
          <p className="text-3xl font-bold text-foreground">{formatCurrency(adminStats.avgPayoutPerClaim)}</p>
          <p className="text-xs text-muted-foreground">Per verified claim</p>
        </div>
      </div>

      {/* Platform Distribution */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="elevated-card rounded-xl p-6">
          <h3 className="text-sm font-semibold text-foreground mb-4">Partner Platform Distribution</h3>
          <ResponsiveContainer width="100%" height={250}>
            <PieChart>
              <Pie data={platformData} cx="50%" cy="50%" outerRadius={80} dataKey="value" label={({ name, percent }) => `${name} ${(percent * 100).toFixed(0)}%`}>
                {platformData.map((_, i) => <Cell key={i} fill={PIE_COLORS[i]} />)}
              </Pie>
              <Tooltip formatter={(val: number) => val.toLocaleString()} />
            </PieChart>
          </ResponsiveContainer>
        </div>

        <div className="elevated-card rounded-xl p-6">
          <h3 className="text-sm font-semibold text-foreground mb-4">Premium Collected vs Payouts (6 Months)</h3>
          <ResponsiveContainer width="100%" height={250}>
            <BarChart data={adminMonthlyData}>
              <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" />
              <XAxis dataKey="month" tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <YAxis tick={{ fontSize: 12, fill: 'hsl(var(--muted-foreground))' }} />
              <Tooltip formatter={(val: number) => formatCurrency(val)} />
              <Bar dataKey="premiumCollected" fill="hsl(var(--primary))" radius={[4, 4, 0, 0]} name="Premium" />
              <Bar dataKey="payouts" fill="hsl(var(--danger, 0, 85%, 55%))" radius={[4, 4, 0, 0]} name="Payouts" />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="elevated-card rounded-xl p-6">
        <h3 className="text-sm font-semibold text-foreground mb-2">{t('exportData')}</h3>
        <p className="text-sm text-muted-foreground mb-4">Download all platform data for reporting and analysis</p>
        <div className="flex flex-wrap gap-3">
          <Button onClick={downloadCSV} variant="outline" className="gap-2 btn-3d">
            <Download className="h-4 w-4" />
            {t('downloadCSV')}
          </Button>
          <Button onClick={downloadPDF} variant="outline" className="gap-2 btn-3d">
            <Download className="h-4 w-4" />
            {t('downloadPDF')}
          </Button>
        </div>
      </div>
    </div>
  );
}
